---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB5z1rGQ5gI4SJqB7nn9e88uu1n1dZ1UAAxlD7cEGJRACzULfndDjj6rO8Gpe817NUXJ4PNV3vE/d6L7YmG2IDmYEuqX865+WCrwi+ObQHM4imjUqVuTsOYMSweRAk3dQQCG3j8zEi+LpiYkTxf5SOWHN71j01klu5Jsp0CO1du5saSE6hSIczZCIaIpolk9hoZ8Pxf4iZKE52kCSHaCnSr4b9ldVO3Z4BKIQt2p7hXn9z/PYOBlt1qdJU7lxWP0ittC+9t2IuFuJ04Brx6qZEjATwY11Kg7HZt4teccQT0Z9V4lKM8IznHIS/3ulJ7xa568ls0JxyKmmyoBZVgcabqfxoLOgWkG+xDIfvH25tqnyQ8xzcMULzjSlfS6b4ebg4a8tToqyEr8CPCV3sM/2UFyUusEvuVziCylzqD4c7c5MdQ7RmHUpug+IhN+ximDa6dGkpnG/y1IKVqTHqJhcYN4zq0f8wX7Mov38jzzL5R9PW0vRAMm7PJNzlj9pEaSG0cq7GWedgmtUFBV1mY0UwMk/t/4SqlWa/7MPtVAwLjDya0dTmxVuELdUFzJpTFewCrPT48dcmn+m+R+zsShcVqqgYRAFTSai/zu62Z19OsUEQSs+SEE8pJOp5FWnIFn3EynxgOPnUpY9GXjMYVlsWvGvvjWOAwKVRsxknrm61ROe5Ahlxd2XjyfNlezT7oQzDAsjQCvixp79vZaHhpCliOAH/lMs4FnVPek/mMJ8gtdNZiae6OnPQu
    admin-user: AgB6h9R026Dgw1J/H+0DCigU5nZ25knPQCbdRba1OA+yJamnOpDTr8GjtknqArHZnadsMxjIppOyH5vf+bpy0DYzJwyEYDybEfDpblEzLjEJgUmJRqMdzlVjVvYUtv0TPx5iy15/7Nx8t3fvg7iXWyHDdCRz7VDYogd8H+Ns+/AcdTlfHnq4yZRljOfKUM8MabLlmD+KsZGHZevZ+05Nfumft3Wm5fJLyK/pNUE7w3/BpEMTXg6A51J+cCSEDeDFDdO8v0DZANJf09CKfk3Y++E500BfojsvaTY6514+vhA7BSptK1Lmpb259lOxaMkClvAYJ/vSqaSDRRu0hVRHLthx0plYvlPX1LJ+HF67bBn3H/nbhbHKenuRLnYlqCJqRIrEkD2AiocfE9CqbUWUQTdw8x55yVsFrAkP53m6Tii8rSuo1tX/DLHIOImSyDDEMgecz0OMn5ptd8tUITA4EoFrzT32SIIWMH2Fd8OLzrTilVshUyc5xhdykcedYq0dyPYHi0P1spHOrF2oMt5e4oJVzj2JRKFITLM4AcAAwFXqriuzSGiSbNUJ/mhyxMeQLaG6+E8DaPfjWEmRnvU409SLg4Z7Uus/evDMNvGt2Mp71bQ0Nm2TecHXr2A6Q/XzBPnz8wn+i9l3in4NAaBmxbNWFlFyOPpKcNtn3iopky49AyvxsGG1vkIFh7Mr9a+wZW4HkaQZ7Q==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
