---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAI+e7vQ4yFCqKpvZxr+q2TNvFeh9Z0nUYNLIX7JXVSYXlHQ5cwNDVghPm1uUKTqMlAYHh2ScvH2OBM8mEAf8hU/p5viz/jVbTJKY7Bq6tvm6VT204nyBBLAOU2K2M/7xNgiqmp5kg+fxLpCKixJhX+cj3EbY6NH6AsjRDkkjUU5bZPetmqyt9ZKdWScLiyQDlwpa7tWPqJkldEfKRPbQCit50n1Mpb29QB+qabRtCsoyJtvJd0muE+PubcnQ8e9gkv5JvvoxyJCCFpgn/DNxBxyHouX1h4A5uuiAqAdixMDSAD70/lMfCnVd8EXB7+mmAow84lVhQ0FteYudFfvK0A7vahFGf1uQ2sm8UDO2ItX0WbRNZI45o+XXWOhqKRRQdTB/curLB5BTPWV9/KvfJkDKKtXgnLpD4MrDfyE2vCpFTP9KrFVhZpf65f+lW6yyCBnRKtr1+4QnwybVs8Dwqd6IADBO86yy5pVFVLRacDqfDWIX5p2vOLoBxADgMFMdJ3I7VQQFxvwYvEMOnQQ/qMtgcUVIds3zilaTdGQLITY2Yio54uNmBeADaC3Rb6Q8cKFeqCtN+cQ6S4QiK//KtdPB/JspsR6TJp6LqfkGG4tfHBX5xMVzhQBC6LdbWsVR0m0Owx6XbpaRjZXcvPYfYNr2NWb16hB/+WaGej9jqRRVIZ+ZPItc/5fiw7Li3O2St881zptSN6pNkni0BBqT4+P5K0SkZQafC+3JFh60kpxkC/F2VlRUHMUh5GPqXnBN0rdlIXJBjP0gn1xJX11Yh3
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
