apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"talos-2jn-7he",
          "paths":["/var/mnt/minecraft"]
        },
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/opt/local-path-provisioner"]
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0770 -p "$VOL_DIR"
    case "$VOL_DIR" in
      */n8n/n8n-data/*)
        chown 1000:1000 "$VOL_DIR"
        ;;
      */crafty-controller/crafty-data/*|*/home-assistant/home-assistant-config/*)
        chown 0:0 "$VOL_DIR"
        ;;
      *)
        chown 0:0 "$VOL_DIR"
        ;;
    esac
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox:1.37.0@sha256:9532d8c39891ca2ecde4d30d7710e01fb739c87a8b9299685c63704296b16028
        imagePullPolicy: IfNotPresent
