apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cloudflared-home-assistant-host
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  egress:
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
