apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-n8n-home-assistant
  namespace: n8n
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: n8n
  egress:
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
