apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/bart-kochanowicz/homelab.git
    targetRevision: main
    path: system/app-namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
