apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.thecavespace.com
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex.github.clientID
          clientSecret: $dex.github.clientSecret
          redirectURI: https://argocd.thecavespace.com/api/dex/callback
          loadAllGroups: false
  kustomize.buildOptions: "--enable-helm"
  timeout.reconciliation: "60s"
  repo.server.timeout.seconds: "60"
  application.instanceLabelKey: argocd.argoproj.io/instance
  admin.enabled: "false"
  application.sync.policy.default: |
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
