apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientID: AgAzKup62qrU7Tj9rIRBJiJ0XiHBmcYEWi0NWf/5Kd9ARr1VR4hXn05PfxkOHSgpMSuYeQf2HDiwDztvEda8N9E+3DaBok4xAlX//NIxWUu3wyZMw/QnWqIP4EQfOZTOZrUH0//RJ7D/40DWu9xdOu6lfJpjupeiVd0EHL8GdUTWW/y1qAx9S9fZ8MW7RP+TZNPxBNrGhmc+dAER1S12bI0ksrrAkQUqwy8E85KBG0pj9x+vP37Cieyaj7PhiX/NUz2XuxBfg7fAI1qbe9m9EJ/+gZS6Syt5oL180/PPY1uJphwPlVuWeOLc8Kk2EZZplsTb75CvecifguvpZTmWOJU1m8JVQA3FuwbP3D9BPxCnSS/PlIYHWKAx8YWKeNOL8AZZG3rGciTV3WGcX4+RAcvFGXYcDzCG++4tajp5/jPC46FyDPTyr9PnnEv1DS0zIu2coMlbWsXTJSmkCAWFA4kA/5RiuCNPJY9JlytXnxeQ29VbBGd2RibreblQM+DaHAdNSRaaT/WNpMAJ1ghhM7MJABMpCvdoD34yeH1vjGEuymAAPD8H1nYceeapUx7cx1MXL5JnqPHEy6ZbB0F3nXtg1rQ/pWXM4N3PwsHJsXFpR5ysX9+j0cMZ/GVbkXgmDcQvsF2N09p2cNu/jssx3K2lH3YZ/7Mp+mcdl94AFC0H27COQ/tBZOu1v0dnM2Tb/9jcAf985jaWzhGR+9ijiPFxjR9nWw==
    dex.github.clientSecret: AgA+jIIFQ6BKDKuv4MsyNjrzH4QYGuCoKxsaJUdnBARZPsqJX+yR9/mpK+xi+yWc1zaPNXxkH3UR+4rrocwR9yyjvxmQgw1HsUOICUe+DoPUXj/KVGFTfw+zfDeMxesLOZNmEyIlQyo/rzmyZ5paiF05P32FaWfdIpCm3fVS1OMOLtfdjUw65ddu9dMdcHbxLP3zrGDLOQl3Prk75K/Cd79mgFT73ypjGS2YX90TSlKPqdRhgXXkXaPZD9aWm41/4M5uxE5L7MiVhCbJQMCjFxms7SRCGNIXjlaijSLpLjvu+j/HPRJmA8r/HX534UGCqPq+0zb1s0DMm+V/TtrIclcbAhvSK4IZQORTtTrc0HKwvbGlurCGOrOk61eMaST2Pb2ejmhLkNfVStPEc2gzQSrKauKb1T514eiHRbyApbFx5c1sm/trB6yFM+J5X+7ZkQbm82u057+gIsjr7ao17eoY/JbYfIr+ahlVwANjsAJ2NIrdTN91kiUs3EFdbA9zJFixJLBzZX1+7MO459HW+kOSn7n1zCGKt641XUW/jrFqrI7Bwr8zNkuwyY2OJs2buyo7GeF1Cu7eXGYuSN7UOnWecEV/BPmw5042dcFDtPIKpUVfIaa/7aBWVpoVGuF8Qc9l3bZh9lkGt9/dRxCqRAYcneB2tE56y9wpxpt0DqEkccwUcCofOPxSunrtZRqkm06k8Welhsb1ZSMGtHPK5x552ubQ6X6pH+a4s/5TT+rfxVRzCQTxOksj
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
