apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - projects.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-sso-sealed-secret.yaml
  - argocd-bootstrap.yaml
  - applicationset.yaml
  - app-namespaces.yaml
  - sealed-secrets.yaml
  - cert-manager.yaml
  - cert-manager-ca.yaml
  - local-path-provisioner.yaml
  - cloudflared.yaml
  - monitoring-crds.yaml
  - monitoring.yaml
  - network-policies.yaml
